#*** Correct Rules ***
# PROXIMITY_DISTANCE = 100
# FOLLOW_DISTANCE = 120

# PROXIMITY_FRAMES = 30
# FOLLOW_FRAMES = 40
# PERSISTENCE_FRAMES = 80
# AGGRESSIVE_SPEED_THRESHOLD = 25      # pixels per frame
# AGGRESSIVE_DISTANCE_DROP = 40        # pixels
# AGGRESSIVE_FRAMES = 5                # short burst


#***Rules for Demo***
# Proximity
PROXIMITY_DISTANCE = 140
PROXIMITY_FRAMES = 15

# Following
FOLLOW_DISTANCE = 160
FOLLOW_FRAMES = 20

# Aggressive Movement
AGGRESSIVE_SPEED_THRESHOLD = 15
AGGRESSIVE_DISTANCE_DROP = 20
AGGRESSIVE_FRAMES = 3
